CREATE TABLE actor
(
    firstname text NOT NULL,
    lastname text NOT NULL,
    CONSTRAINT actor_pkey PRIMARY KEY (firstname, lastname)
);

INSERT INTO actor (firstname, lastname) VALUES ('Ross', 'Bagdasarian');
INSERT INTO actor (firstname, lastname) VALUES ('Anthony', 'Daniels');
INSERT INTO actor (firstname, lastname) VALUES ('Daisuke', 'Katô');
INSERT INTO actor (firstname, lastname) VALUES ('Joseph', 'Cotten');
INSERT INTO actor (firstname, lastname) VALUES ('Steven', 'Zaillian');
INSERT INTO actor (firstname, lastname) VALUES ('Ernest', 'Lehman');
INSERT INTO actor (firstname, lastname) VALUES ('Embeth', 'Davidtz');
INSERT INTO actor (firstname, lastname) VALUES ('Cary', 'Grant');
INSERT INTO actor (firstname, lastname) VALUES ('Gladys', 'George');
INSERT INTO actor (firstname, lastname) VALUES ('Thomas', 'Mitchell (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Barry', 'Pepper');
INSERT INTO actor (firstname, lastname) VALUES ('Philip', 'Kaufman');
INSERT INTO actor (firstname, lastname) VALUES ('Larry', 'Wachowski');
INSERT INTO actor (firstname, lastname) VALUES ('Quentin', 'Tarantino');
INSERT INTO actor (firstname, lastname) VALUES ('Joerg', 'Stadler');
INSERT INTO actor (firstname, lastname) VALUES ('Henry', 'Jones (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Kokuten', 'Kodo');
INSERT INTO actor (firstname, lastname) VALUES ('Gregory', 'Peck');
INSERT INTO actor (firstname, lastname) VALUES ('Paul', 'Giamatti');
INSERT INTO actor (firstname, lastname) VALUES ('Talia', 'Shire');
INSERT INTO actor (firstname, lastname) VALUES ('Norman', 'Rossington');
INSERT INTO actor (firstname, lastname) VALUES ('Holt', 'McCallany');
INSERT INTO actor (firstname, lastname) VALUES ('Sue', 'Casey');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Ruddock');
INSERT INTO actor (firstname, lastname) VALUES ('Jiro', 'Kumagai');
INSERT INTO actor (firstname, lastname) VALUES ('James', 'Whitmore');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Darabont');
INSERT INTO actor (firstname, lastname) VALUES ('Roger', 'Avary');
INSERT INTO actor (firstname, lastname) VALUES ('Frankie', 'Faison');
INSERT INTO actor (firstname, lastname) VALUES ('Peter', 'Bull (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Curtis', 'Hanson');
INSERT INTO actor (firstname, lastname) VALUES ('Charles', 'Scorsese');
INSERT INTO actor (firstname, lastname) VALUES ('Suzy', 'Amis');
INSERT INTO actor (firstname, lastname) VALUES ('Marc', 'Gray');
INSERT INTO actor (firstname, lastname) VALUES ('Mischa', 'Barton');
INSERT INTO actor (firstname, lastname) VALUES ('Henry', 'Oscar');
INSERT INTO actor (firstname, lastname) VALUES ('Robert', 'Mulligan');
INSERT INTO actor (firstname, lastname) VALUES ('Caroline', 'Goodall');
INSERT INTO actor (firstname, lastname) VALUES ('Chuck', 'Low (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Gus', 'Schilling');
INSERT INTO actor (firstname, lastname) VALUES ('Noel', 'Langley');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'McIntire (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Amerigo', 'Fontani');
INSERT INTO actor (firstname, lastname) VALUES ('Slim', 'Pickens');
INSERT INTO actor (firstname, lastname) VALUES ('Stanley', 'Kubrick');
INSERT INTO actor (firstname, lastname) VALUES ('Alan', 'Ball (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Barbara', 'Bel Geddes');
INSERT INTO actor (firstname, lastname) VALUES ('Neil', 'Giuntoli');
INSERT INTO actor (firstname, lastname) VALUES ('Kasi', 'Lemmons');
INSERT INTO actor (firstname, lastname) VALUES ('Lee', 'Patrick');
INSERT INTO actor (firstname, lastname) VALUES ('Ray', 'Liotta');
INSERT INTO actor (firstname, lastname) VALUES ('Adam', 'Goldberg');
INSERT INTO actor (firstname, lastname) VALUES ('William', 'Hootkins');
INSERT INTO actor (firstname, lastname) VALUES ('Charley', 'Grapewin');
INSERT INTO actor (firstname, lastname) VALUES ('Tom', 'Helmore');
INSERT INTO actor (firstname, lastname) VALUES ('Norbert', 'Weisser');
INSERT INTO actor (firstname, lastname) VALUES ('Donnie', 'Wahlberg');
INSERT INTO actor (firstname, lastname) VALUES ('Roberto', 'Benigni');
INSERT INTO actor (firstname, lastname) VALUES ('Edith', 'Head');
INSERT INTO actor (firstname, lastname) VALUES ('Margaret', 'Hamilton');
INSERT INTO actor (firstname, lastname) VALUES ('Jim', 'Uhls');
INSERT INTO actor (firstname, lastname) VALUES ('Jack', 'Nicholson');
INSERT INTO actor (firstname, lastname) VALUES ('Max', 'Martini');
INSERT INTO actor (firstname, lastname) VALUES ('Gastone', 'Moschin');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Overton');
INSERT INTO actor (firstname, lastname) VALUES ('Ruth', 'Warrick');
INSERT INTO actor (firstname, lastname) VALUES ('Anthony', 'Quinn');
INSERT INTO actor (firstname, lastname) VALUES ('Keanu', 'Reeves');
INSERT INTO actor (firstname, lastname) VALUES ('Edward', 'Norton');
INSERT INTO actor (firstname, lastname) VALUES ('Paul', 'Freeman (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Marlon', 'Brando');
INSERT INTO actor (firstname, lastname) VALUES ('Maria', 'de Medeiros');
INSERT INTO actor (firstname, lastname) VALUES ('Diane', 'Keaton');
INSERT INTO actor (firstname, lastname) VALUES ('Tim', 'Robbins');
INSERT INTO actor (firstname, lastname) VALUES ('Michael', 'Berryman');
INSERT INTO actor (firstname, lastname) VALUES ('Sam', 'Robards');
INSERT INTO actor (firstname, lastname) VALUES ('William', 'Redfield');
INSERT INTO actor (firstname, lastname) VALUES ('Vic', 'Tablian');
INSERT INTO actor (firstname, lastname) VALUES ('Laura', 'Lovelace');
INSERT INTO actor (firstname, lastname) VALUES ('Humphrey', 'Bogart');
INSERT INTO actor (firstname, lastname) VALUES ('Collin', 'Wilcox Paxton');
INSERT INTO actor (firstname, lastname) VALUES ('Katherine', 'Trosper');
INSERT INTO actor (firstname, lastname) VALUES ('Dashiell', 'Hammett');
INSERT INTO actor (firstname, lastname) VALUES ('Dan', 'Hedaya');
INSERT INTO actor (firstname, lastname) VALUES ('Ray', 'Anthony Parker');
INSERT INTO actor (firstname, lastname) VALUES ('Barton', 'MacLane');
INSERT INTO actor (firstname, lastname) VALUES ('Ellen', 'Corby');
INSERT INTO actor (firstname, lastname) VALUES ('James', 'Ellroy');
INSERT INTO actor (firstname, lastname) VALUES ('Audrey', 'Hepburn');
INSERT INTO actor (firstname, lastname) VALUES ('Wes', 'Bentley');
INSERT INTO actor (firstname, lastname) VALUES ('James', 'Anderson (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Abe', 'Vigoda');
INSERT INTO actor (firstname, lastname) VALUES ('Béatrice', 'Macola');
INSERT INTO actor (firstname, lastname) VALUES ('Harrison', 'Ford');
INSERT INTO actor (firstname, lastname) VALUES ('Tim', 'Roth');
INSERT INTO actor (firstname, lastname) VALUES ('Isao', 'Kimura');
INSERT INTO actor (firstname, lastname) VALUES ('Laurence', 'Fishburne');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Capra');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'DiLeo');
INSERT INTO actor (firstname, lastname) VALUES ('Glenn', 'Fitzgerald');
INSERT INTO actor (firstname, lastname) VALUES ('Chuck', 'Palahniuk');
INSERT INTO actor (firstname, lastname) VALUES ('Thelma', 'Ritter');
INSERT INTO actor (firstname, lastname) VALUES ('Jeffrey', 'Lane');
INSERT INTO actor (firstname, lastname) VALUES ('James', 'Caan');
INSERT INTO actor (firstname, lastname) VALUES ('Masha', 'Skorobogatov');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Michael Hayes');
INSERT INTO actor (firstname, lastname) VALUES ('Everett', 'Sloane');
INSERT INTO actor (firstname, lastname) VALUES ('Zach', 'Grenier');
INSERT INTO actor (firstname, lastname) VALUES ('Wolf', 'Kahler');
INSERT INTO actor (firstname, lastname) VALUES ('Peter', 'Sallis');
INSERT INTO actor (firstname, lastname) VALUES ('Edward', 'Kowalczyk');
INSERT INTO actor (firstname, lastname) VALUES ('Nick', 'Park');
INSERT INTO actor (firstname, lastname) VALUES ('Giustino', 'Durano');
INSERT INTO actor (firstname, lastname) VALUES ('Brock', 'Peters');
INSERT INTO actor (firstname, lastname) VALUES ('Eva', 'Marie Saint');
INSERT INTO actor (firstname, lastname) VALUES ('Stuart', 'Rudin');
INSERT INTO actor (firstname, lastname) VALUES ('Hal', 'Galili');
INSERT INTO actor (firstname, lastname) VALUES ('Dorothy', 'Comingore');
INSERT INTO actor (firstname, lastname) VALUES ('Jesslyn', 'Fax');
INSERT INTO actor (firstname, lastname) VALUES ('Annette', 'Bening');
INSERT INTO actor (firstname, lastname) VALUES ('Steven', 'Spielberg');
INSERT INTO actor (firstname, lastname) VALUES ('Lan', 'Fendors');
INSERT INTO actor (firstname, lastname) VALUES ('Amanda', 'Plummer');
INSERT INTO actor (firstname, lastname) VALUES ('Harper', 'Lee');
INSERT INTO actor (firstname, lastname) VALUES ('Shmulik', 'Levy (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Martin', 'Balsam');
INSERT INTO actor (firstname, lastname) VALUES ('Kevin', 'Costner');
INSERT INTO actor (firstname, lastname) VALUES ('Stuart', 'Saunders (II)');
INSERT INTO actor (firstname, lastname) VALUES ('Yoshio', 'Inaba');
INSERT INTO actor (firstname, lastname) VALUES ('Matt', 'Doran');
INSERT INTO actor (firstname, lastname) VALUES ('Robert', 'Duvall');
INSERT INTO actor (firstname, lastname) VALUES ('Billie', 'Burke');
INSERT INTO actor (firstname, lastname) VALUES ('Meat', 'Loaf');
INSERT INTO actor (firstname, lastname) VALUES ('Irene', 'Winston');
INSERT INTO actor (firstname, lastname) VALUES ('Al', 'Lettieri');
INSERT INTO actor (firstname, lastname) VALUES ('Giorgio', 'Cantarini');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Cazale');
INSERT INTO actor (firstname, lastname) VALUES ('Anthony', 'Quayle');
INSERT INTO actor (firstname, lastname) VALUES ('Robert', 'Bloch');
INSERT INTO actor (firstname, lastname) VALUES ('Carrie-Anne', 'Moss');
INSERT INTO actor (firstname, lastname) VALUES ('Krzysztof', 'Luft');
INSERT INTO actor (firstname, lastname) VALUES ('David', 'Proval');
INSERT INTO actor (firstname, lastname) VALUES ('Thomas', 'Keneally');
INSERT INTO actor (firstname, lastname) VALUES ('Mark', 'Rolston');
INSERT INTO actor (firstname, lastname) VALUES ('Al', 'Pacino');
INSERT INTO actor (firstname, lastname) VALUES ('Sidney', 'Lumet');
INSERT INTO actor (firstname, lastname) VALUES ('Peter', 'Lorre');
INSERT INTO actor (firstname, lastname) VALUES ('Larry', 'Brandenburg');
INSERT INTO actor (firstname, lastname) VALUES ('Bert', 'Lahr');
INSERT INTO actor (firstname, lastname) VALUES ('Samia', 'Shoaib');
INSERT INTO actor (firstname, lastname) VALUES ('Olivia', 'Williams');
INSERT INTO actor (firstname, lastname) VALUES ('Vera', 'Miles');
INSERT INTO actor (firstname, lastname) VALUES ('Shinobu', 'Hashimoto');
INSERT INTO actor (firstname, lastname) VALUES ('Peter', 'O''Toole');
INSERT INTO actor (firstname, lastname) VALUES ('Ben', 'Kingsley');
INSERT INTO actor (firstname, lastname) VALUES ('Bruce', 'Norris');
INSERT INTO actor (firstname, lastname) VALUES ('Lorraine', 'Bracco');
INSERT INTO actor (firstname, lastname) VALUES ('Richard', 'Bright');
INSERT INTO actor (firstname, lastname) VALUES ('Horton', 'Foote');
INSERT INTO actor (firstname, lastname) VALUES ('George', 'Voskovec');
INSERT INTO actor (firstname, lastname) VALUES ('Steve', 'Rankin');
INSERT INTO actor (firstname, lastname) VALUES ('Scott', 'Glenn');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Rhys-Davies');
INSERT INTO actor (firstname, lastname) VALUES ('Paul', 'Guilfoyle (II)');
INSERT INTO actor (firstname, lastname) VALUES ('Burr', 'Steers');
INSERT INTO actor (firstname, lastname) VALUES ('Joseph', 'Stefano');
INSERT INTO actor (firstname, lastname) VALUES ('David', 'Aston');
INSERT INTO actor (firstname, lastname) VALUES ('Toshirô', 'Mifune');
INSERT INTO actor (firstname, lastname) VALUES ('Richard', 'Conte');
INSERT INTO actor (firstname, lastname) VALUES ('Akira', 'Kurosawa');
INSERT INTO actor (firstname, lastname) VALUES ('Henry', 'Travers');
INSERT INTO actor (firstname, lastname) VALUES ('Kevin', 'Pollak');
INSERT INTO actor (firstname, lastname) VALUES ('Ted', 'Danson');
INSERT INTO actor (firstname, lastname) VALUES ('David', 'Strathairn');
INSERT INTO actor (firstname, lastname) VALUES ('David', 'Prowse');
INSERT INTO actor (firstname, lastname) VALUES ('Pierce', 'Brosnan');
INSERT INTO actor (firstname, lastname) VALUES ('Bruce', 'Willis');
INSERT INTO actor (firstname, lastname) VALUES ('Ed', 'Binns');
INSERT INTO actor (firstname, lastname) VALUES ('Orson', 'Welles');
INSERT INTO actor (firstname, lastname) VALUES ('Leonid', 'Kinskey');
INSERT INTO actor (firstname, lastname) VALUES ('Gloria', 'Foster');
INSERT INTO actor (firstname, lastname) VALUES ('Victor', 'Fleming');
INSERT INTO actor (firstname, lastname) VALUES ('Mark', 'Ivanir');
INSERT INTO actor (firstname, lastname) VALUES ('Jack', 'Warden');
INSERT INTO actor (firstname, lastname) VALUES ('Keenan', 'Wynn');
INSERT INTO actor (firstname, lastname) VALUES ('Alec', 'Guinness');
INSERT INTO actor (firstname, lastname) VALUES ('Josip', 'Elic');
INSERT INTO actor (firstname, lastname) VALUES ('Francesca', 'De Sapio');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Megna');
INSERT INTO actor (firstname, lastname) VALUES ('Bo', 'Goldman');
INSERT INTO actor (firstname, lastname) VALUES ('Firdous', 'Bamji (II)');
INSERT INTO actor (firstname, lastname) VALUES ('Jeremy', 'Davies');
INSERT INTO actor (firstname, lastname) VALUES ('Seiji', 'Miyaguchi');
INSERT INTO actor (firstname, lastname) VALUES ('Jodi', 'Dawson');
INSERT INTO actor (firstname, lastname) VALUES ('Crahan', 'Denton');
INSERT INTO actor (firstname, lastname) VALUES ('Ward', 'Bond');
INSERT INTO actor (firstname, lastname) VALUES ('Nicoletta', 'Braschi');
INSERT INTO actor (firstname, lastname) VALUES ('Julian', 'Arahanga');
INSERT INTO actor (firstname, lastname) VALUES ('James', 'Cromwell');
INSERT INTO actor (firstname, lastname) VALUES ('Kevin', 'Spacey');
INSERT INTO actor (firstname, lastname) VALUES ('Pietro', 'De Silva');
INSERT INTO actor (firstname, lastname) VALUES ('Thomas', 'Harris');
INSERT INTO actor (firstname, lastname) VALUES ('Janet', 'Leigh');
INSERT INTO actor (firstname, lastname) VALUES ('Dooley', 'Wilson');
INSERT INTO actor (firstname, lastname) VALUES ('Jessie', 'Royce Landis');
INSERT INTO actor (firstname, lastname) VALUES ('Robert', 'Webber (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Belinda', 'Mcclory');
INSERT INTO actor (firstname, lastname) VALUES ('Ray', 'Collins (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Murray', 'Burnett');
INSERT INTO actor (firstname, lastname) VALUES ('Dennis', 'Farina');
INSERT INTO actor (firstname, lastname) VALUES ('Alfred', 'Molina');
INSERT INTO actor (firstname, lastname) VALUES ('Agnes', 'Moorehead');
INSERT INTO actor (firstname, lastname) VALUES ('Barry', 'Del Sherman');
INSERT INTO actor (firstname, lastname) VALUES ('Sean', 'Connery');
INSERT INTO actor (firstname, lastname) VALUES ('Christopher', 'McQuarrie (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Mary', 'Astor');
INSERT INTO actor (firstname, lastname) VALUES ('Giovanni', 'Ribisi');
INSERT INTO actor (firstname, lastname) VALUES ('Gianni', 'Russo');
INSERT INTO actor (firstname, lastname) VALUES ('Anthony', 'Hopkins');
INSERT INTO actor (firstname, lastname) VALUES ('Tony', 'Darrow');
INSERT INTO actor (firstname, lastname) VALUES ('Erskine', 'Sanford');
INSERT INTO actor (firstname, lastname) VALUES ('Havis', 'Davenport');
INSERT INTO actor (firstname, lastname) VALUES ('Jerome', 'Cowan');
INSERT INTO actor (firstname, lastname) VALUES ('Paul', 'Fix');
INSERT INTO actor (firstname, lastname) VALUES ('Patrick', 'McVey');
INSERT INTO actor (firstname, lastname) VALUES ('Philip', 'Van Zandt');
INSERT INTO actor (firstname, lastname) VALUES ('Tom', 'Hanks');
INSERT INTO actor (firstname, lastname) VALUES ('Jude', 'Ciccolella');
INSERT INTO actor (firstname, lastname) VALUES ('Simon', 'Oakland');
INSERT INTO actor (firstname, lastname) VALUES ('Michael', 'Curtiz');
INSERT INTO actor (firstname, lastname) VALUES ('Philip', 'Ober');
INSERT INTO actor (firstname, lastname) VALUES ('Anthony', 'Perkins');
INSERT INTO actor (firstname, lastname) VALUES ('José', 'Ferrer');
INSERT INTO actor (firstname, lastname) VALUES ('Stephen', 'Baldwin');
INSERT INTO actor (firstname, lastname) VALUES ('Sydney', 'Greenstreet');
INSERT INTO actor (firstname, lastname) VALUES ('Jack', 'Haley (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Joe', 'Pesci');
INSERT INTO actor (firstname, lastname) VALUES ('Des', 'Webb');
INSERT INTO actor (firstname, lastname) VALUES ('Thora', 'Birch');
INSERT INTO actor (firstname, lastname) VALUES ('Kevin', 'Scott Mack');
INSERT INTO actor (firstname, lastname) VALUES ('Harvey', 'Keitel');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Faylen');
INSERT INTO actor (firstname, lastname) VALUES ('Michel', 'Ray');
INSERT INTO actor (firstname, lastname) VALUES ('Ray', 'Bolger');
INSERT INTO actor (firstname, lastname) VALUES ('Pat', 'Walshe');
INSERT INTO actor (firstname, lastname) VALUES ('Vincenzo', 'Cerami');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Gavin');
INSERT INTO actor (firstname, lastname) VALUES ('Jeffrey', 'DeMunn');
INSERT INTO actor (firstname, lastname) VALUES ('Peter', 'Sellers');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Cho');
INSERT INTO actor (firstname, lastname) VALUES ('Gil', 'Bellows');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Qualen');
INSERT INTO actor (firstname, lastname) VALUES ('Robert', 'Bolt');
INSERT INTO actor (firstname, lastname) VALUES ('Brad', 'Pitt');
INSERT INTO actor (firstname, lastname) VALUES ('Jack', 'Creley');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Hollis (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Ken', 'Kenny (II)');
INSERT INTO actor (firstname, lastname) VALUES ('Lurene', 'Tuttle');
INSERT INTO actor (firstname, lastname) VALUES ('Ron', 'Rifkin');
INSERT INTO actor (firstname, lastname) VALUES ('Christine', 'Estabrook');
INSERT INTO actor (firstname, lastname) VALUES ('Minoru', 'Chiaki');
INSERT INTO actor (firstname, lastname) VALUES ('David', 'Fincher');
INSERT INTO actor (firstname, lastname) VALUES ('Josephine', 'Hutchinson');
INSERT INTO actor (firstname, lastname) VALUES ('Harry', 'Nehring');
INSERT INTO actor (firstname, lastname) VALUES ('Leigh', 'Brackett');
INSERT INTO actor (firstname, lastname) VALUES ('Don', 'Fellows');
INSERT INTO actor (firstname, lastname) VALUES ('Liam', 'Neeson');
INSERT INTO actor (firstname, lastname) VALUES ('Georgine', 'Darcy');
INSERT INTO actor (firstname, lastname) VALUES ('Toni', 'Collette');
INSERT INTO actor (firstname, lastname) VALUES ('Jackie', 'Chan');
INSERT INTO actor (firstname, lastname) VALUES ('Gina', 'Mastrogiacomo');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Sivero');
INSERT INTO actor (firstname, lastname) VALUES ('Shelagh', 'Fraser');
INSERT INTO actor (firstname, lastname) VALUES ('Scatman', 'Crothers');
INSERT INTO actor (firstname, lastname) VALUES ('Allison', 'Janney');
INSERT INTO actor (firstname, lastname) VALUES ('Ara', 'Celi');
INSERT INTO actor (firstname, lastname) VALUES ('George', '''Red'' Schwartz');
INSERT INTO actor (firstname, lastname) VALUES ('Philip', 'Coolidge');
INSERT INTO actor (firstname, lastname) VALUES ('Kim', 'Basinger');
INSERT INTO actor (firstname, lastname) VALUES ('William', 'Duell');
INSERT INTO actor (firstname, lastname) VALUES ('Conrad', 'Veidt');
INSERT INTO actor (firstname, lastname) VALUES ('Elisabeth', 'Granli');
INSERT INTO actor (firstname, lastname) VALUES ('Gloria', 'Grahame');
INSERT INTO actor (firstname, lastname) VALUES ('Guy', 'Pearce');
INSERT INTO actor (firstname, lastname) VALUES ('William', 'Sadler');
INSERT INTO actor (firstname, lastname) VALUES ('Robert', 'Rodat');
INSERT INTO actor (firstname, lastname) VALUES ('Estelle', 'Evans (II)');
INSERT INTO actor (firstname, lastname) VALUES ('Paul', 'Bartel');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Marley');
INSERT INTO actor (firstname, lastname) VALUES ('Wendell', 'Corey');
INSERT INTO actor (firstname, lastname) VALUES ('Kenneth', 'Fortescue');
INSERT INTO actor (firstname, lastname) VALUES ('Thomas', 'Narcejac');
INSERT INTO actor (firstname, lastname) VALUES ('Helena', 'Bonham Carter');
INSERT INTO actor (firstname, lastname) VALUES ('Madeleine', 'LeBeau');
INSERT INTO actor (firstname, lastname) VALUES ('Karen', 'Allen');
INSERT INTO actor (firstname, lastname) VALUES ('Carl', 'Bressler');
INSERT INTO actor (firstname, lastname) VALUES ('Graham', 'Beckel');
INSERT INTO actor (firstname, lastname) VALUES ('Haley', 'Joel Osment');
INSERT INTO actor (firstname, lastname) VALUES ('Malgoscha', 'Gebel');
INSERT INTO actor (firstname, lastname) VALUES ('Tom', 'Sizemore');
INSERT INTO actor (firstname, lastname) VALUES ('Peter', 'Iacangelo');
INSERT INTO actor (firstname, lastname) VALUES ('Ingrid', 'Bergman');
INSERT INTO actor (firstname, lastname) VALUES ('Mort', 'Mills');
INSERT INTO actor (firstname, lastname) VALUES ('Uma', 'Thurman');
INSERT INTO actor (firstname, lastname) VALUES ('Alice', 'Ghostley');
INSERT INTO actor (firstname, lastname) VALUES ('Matt', 'Damon');
INSERT INTO actor (firstname, lastname) VALUES ('Paul', 'Dillon (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Danny', 'DeVito');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Travolta');
INSERT INTO actor (firstname, lastname) VALUES ('Les', 'Tremayne');
INSERT INTO actor (firstname, lastname) VALUES ('Rock', 'Hudson');
INSERT INTO actor (firstname, lastname) VALUES ('Winona', 'Ryder');
INSERT INTO actor (firstname, lastname) VALUES ('Patricia', 'Hitchcock');
INSERT INTO actor (firstname, lastname) VALUES ('Rand', 'Harper');
INSERT INTO actor (firstname, lastname) VALUES ('Brian', 'Helgeland');
INSERT INTO actor (firstname, lastname) VALUES ('William', 'Alland');
INSERT INTO actor (firstname, lastname) VALUES ('Sam', 'Mendes');
INSERT INTO actor (firstname, lastname) VALUES ('Anthony', 'Heald');
INSERT INTO actor (firstname, lastname) VALUES ('Jonathan', 'Sagall');
INSERT INTO actor (firstname, lastname) VALUES ('Mwako', 'Cumbuka');
INSERT INTO actor (firstname, lastname) VALUES ('Drewe', 'Henley');
INSERT INTO actor (firstname, lastname) VALUES ('Edward', 'Burns (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Ed', 'Begley (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Fort', 'Atkinson');
INSERT INTO actor (firstname, lastname) VALUES ('Rachel', 'Singer');
INSERT INTO actor (firstname, lastname) VALUES ('Richard', 'Hale (II)');
INSERT INTO actor (firstname, lastname) VALUES ('Francis', 'Coppola');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Albertson (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Paul', 'Henreid');
INSERT INTO actor (firstname, lastname) VALUES ('Robert', 'O''Neil (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Sergio', 'Bini Bustric');
INSERT INTO actor (firstname, lastname) VALUES ('Pete', 'Postlethwaite');
INSERT INTO actor (firstname, lastname) VALUES ('Jack', 'Hawkins');
INSERT INTO actor (firstname, lastname) VALUES ('Sara', 'Berner');
INSERT INTO actor (firstname, lastname) VALUES ('Reginald', 'Rose');
INSERT INTO actor (firstname, lastname) VALUES ('Gil', 'Baroni');
INSERT INTO actor (firstname, lastname) VALUES ('Yoshio', 'Tsuchiya');
INSERT INTO actor (firstname, lastname) VALUES ('Ving', 'Rhames');
INSERT INTO actor (firstname, lastname) VALUES ('Murray', 'Alper');
INSERT INTO actor (firstname, lastname) VALUES ('Ronald', 'Lacey');
INSERT INTO actor (firstname, lastname) VALUES ('Don', 'Brockett');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Dimech');
INSERT INTO actor (firstname, lastname) VALUES ('Hugh', 'Miller (II)');
INSERT INTO actor (firstname, lastname) VALUES ('Nicholas', 'Pileggi');
INSERT INTO actor (firstname, lastname) VALUES ('Peter', 'Cushing');
INSERT INTO actor (firstname, lastname) VALUES ('Omar', 'Sharif');
INSERT INTO actor (firstname, lastname) VALUES ('Peter', 'Brocco');
INSERT INTO actor (firstname, lastname) VALUES ('Carol', 'Reed');
INSERT INTO actor (firstname, lastname) VALUES ('Joseph', 'Sweeney');
INSERT INTO actor (firstname, lastname) VALUES ('Carrie', 'Fisher');
INSERT INTO actor (firstname, lastname) VALUES ('Lawrence', 'Hauben');
INSERT INTO actor (firstname, lastname) VALUES ('Keiji', 'Sakakida');
INSERT INTO actor (firstname, lastname) VALUES ('Mary', 'Treen');
INSERT INTO actor (firstname, lastname) VALUES ('Edward', 'Platt');
INSERT INTO actor (firstname, lastname) VALUES ('Clara', 'Blandick');
INSERT INTO actor (firstname, lastname) VALUES ('Judy', 'Garland');
INSERT INTO actor (firstname, lastname) VALUES ('Russell', 'Crowe');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Oz');
INSERT INTO actor (firstname, lastname) VALUES ('Evan', 'Mirand');
INSERT INTO actor (firstname, lastname) VALUES ('Kathryn', 'Mullen');
INSERT INTO actor (firstname, lastname) VALUES ('Joy', 'Page');
INSERT INTO actor (firstname, lastname) VALUES ('Joe', 'Pantoliano');
INSERT INTO actor (firstname, lastname) VALUES ('Phillip', 'Simon');
INSERT INTO actor (firstname, lastname) VALUES ('Horst', 'Buchholz');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Berry');
INSERT INTO actor (firstname, lastname) VALUES ('Benicio', 'Del Toro');
INSERT INTO actor (firstname, lastname) VALUES ('Haruko', 'Toyama');
INSERT INTO actor (firstname, lastname) VALUES ('Takashi', 'Shimura');
INSERT INTO actor (firstname, lastname) VALUES ('George', 'Maguire');
INSERT INTO actor (firstname, lastname) VALUES ('Pierre', 'Boileau');
INSERT INTO actor (firstname, lastname) VALUES ('Todd', 'Karns');
INSERT INTO actor (firstname, lastname) VALUES ('Joseph', 'Ragno');
INSERT INTO actor (firstname, lastname) VALUES ('Eric', 'Stoltz');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Morgan (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Andrzej', 'Seweryn');
INSERT INTO actor (firstname, lastname) VALUES ('Virginia', 'Patton');
INSERT INTO actor (firstname, lastname) VALUES ('Jack', 'Purvis');
INSERT INTO actor (firstname, lastname) VALUES ('Milos', 'Forman');
INSERT INTO actor (firstname, lastname) VALUES ('Ralph', 'Fiennes');
INSERT INTO actor (firstname, lastname) VALUES ('Brian', 'Libby');
INSERT INTO actor (firstname, lastname) VALUES ('Raymond', 'Burr');
INSERT INTO actor (firstname, lastname) VALUES ('Tony', 'Michael Donnelly');
INSERT INTO actor (firstname, lastname) VALUES ('Friedrich', 'von Thun');
INSERT INTO actor (firstname, lastname) VALUES ('Stuart', 'Blumberg');
INSERT INTO actor (firstname, lastname) VALUES ('Konstantin', 'Shayne');
INSERT INTO actor (firstname, lastname) VALUES ('Marcus', 'Chong');
INSERT INTO actor (firstname, lastname) VALUES ('Robert', 'Ellenstein');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Huston');
INSERT INTO actor (firstname, lastname) VALUES ('Philip', 'Van Doren Stern');
INSERT INTO actor (firstname, lastname) VALUES ('Mena', 'Suvari');
INSERT INTO actor (firstname, lastname) VALUES ('Jack', 'Shearer');
INSERT INTO actor (firstname, lastname) VALUES ('Lee', 'Strasberg');
INSERT INTO actor (firstname, lastname) VALUES ('Shane', 'Rimmer');
INSERT INTO actor (firstname, lastname) VALUES ('Kim', 'Novak');
INSERT INTO actor (firstname, lastname) VALUES ('Mark', 'Hamill');
INSERT INTO actor (firstname, lastname) VALUES ('Fernando', 'Sancho (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Phil', 'LaMarr');
INSERT INTO actor (firstname, lastname) VALUES ('Eion', 'Bailey');
INSERT INTO actor (firstname, lastname) VALUES ('Raffaella', 'Lebboroni');
INSERT INTO actor (firstname, lastname) VALUES ('Jonathan', 'Demme');
INSERT INTO actor (firstname, lastname) VALUES ('Francesco', 'Guzzo');
INSERT INTO actor (firstname, lastname) VALUES ('James', 'Mason');
INSERT INTO actor (firstname, lastname) VALUES ('Jared', 'Leto');
INSERT INTO actor (firstname, lastname) VALUES ('Giancarlo', 'Esposito');
INSERT INTO actor (firstname, lastname) VALUES ('Bill', 'Reimbold');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Cady');
INSERT INTO actor (firstname, lastname) VALUES ('Giuliana', 'Lojodice');
INSERT INTO actor (firstname, lastname) VALUES ('Roy', 'Stephens');
INSERT INTO actor (firstname, lastname) VALUES ('Sandra', 'Taylor');
INSERT INTO actor (firstname, lastname) VALUES ('Arthur', 'Kennedy (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Donald', 'Wolfit');
INSERT INTO actor (firstname, lastname) VALUES ('Judith', 'Evelyn');
INSERT INTO actor (firstname, lastname) VALUES ('Gabriel', 'Byrne');
INSERT INTO actor (firstname, lastname) VALUES ('Paul', 'Stewart (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Fortunio', 'Bonanova');
INSERT INTO actor (firstname, lastname) VALUES ('Lionel', 'Barrymore');
INSERT INTO actor (firstname, lastname) VALUES ('Paolo', 'Seganti');
INSERT INTO actor (firstname, lastname) VALUES ('Frances', 'Goodrich');
INSERT INTO actor (firstname, lastname) VALUES ('Irvin', 'Kershner');
INSERT INTO actor (firstname, lastname) VALUES ('Roger', 'Moore');
INSERT INTO actor (firstname, lastname) VALUES ('Jack', 'Klugman');
INSERT INTO actor (firstname, lastname) VALUES ('Vin', 'Diesel');
INSERT INTO actor (firstname, lastname) VALUES ('Curt', 'Bois');
INSERT INTO actor (firstname, lastname) VALUES ('David', 'Lean');
INSERT INTO actor (firstname, lastname) VALUES ('Marisa', 'Paredes');
INSERT INTO actor (firstname, lastname) VALUES ('Paul', 'Goddard (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Fred', 'Sorenson');
INSERT INTO actor (firstname, lastname) VALUES ('Joan', 'Alison');
INSERT INTO actor (firstname, lastname) VALUES ('Yoshio', 'Kosugi (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Ruth', 'White (II)');
INSERT INTO actor (firstname, lastname) VALUES ('Beulah', 'Bondi');
INSERT INTO actor (firstname, lastname) VALUES ('George', 'Coulouris');
INSERT INTO actor (firstname, lastname) VALUES ('Martin', 'Landau');
INSERT INTO actor (firstname, lastname) VALUES ('Denholm', 'Elliott');
INSERT INTO actor (firstname, lastname) VALUES ('Louise', 'Fletcher');
INSERT INTO actor (firstname, lastname) VALUES ('Dylan', 'Bruno');
INSERT INTO actor (firstname, lastname) VALUES ('Leib', 'Lensky');
INSERT INTO actor (firstname, lastname) VALUES ('Robert', 'De Niro');
INSERT INTO actor (firstname, lastname) VALUES ('Patrick', 'Durkin');
INSERT INTO actor (firstname, lastname) VALUES ('Jeremy', 'Bulloch');
INSERT INTO actor (firstname, lastname) VALUES ('Kamatari', 'Fujiwara');
INSERT INTO actor (firstname, lastname) VALUES ('Hugo', 'Weaving');
INSERT INTO actor (firstname, lastname) VALUES ('Chazz', 'Palminteri');
INSERT INTO actor (firstname, lastname) VALUES ('William', 'Windom');
INSERT INTO actor (firstname, lastname) VALUES ('Joel', 'Bissonnette');
INSERT INTO actor (firstname, lastname) VALUES ('Gamil', 'Ratib');
INSERT INTO actor (firstname, lastname) VALUES ('Stephen', 'King');
INSERT INTO actor (firstname, lastname) VALUES ('Chris', 'Cooper (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Ezra', 'Buzzington');
INSERT INTO actor (firstname, lastname) VALUES ('Sterling', 'Hayden');
INSERT INTO actor (firstname, lastname) VALUES ('Glenn', 'Beck');
INSERT INTO actor (firstname, lastname) VALUES ('Claudio', 'Alfonsi');
INSERT INTO actor (firstname, lastname) VALUES ('Peter', 'Mayhew (II)');
INSERT INTO actor (firstname, lastname) VALUES ('Bokuzen', 'Hidari');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Whaley');
INSERT INTO actor (firstname, lastname) VALUES ('Henny', 'Youngman');
INSERT INTO actor (firstname, lastname) VALUES ('Howard', 'Marion-Crawford');
INSERT INTO actor (firstname, lastname) VALUES ('Alex', 'McCrindle');
INSERT INTO actor (firstname, lastname) VALUES ('Peter', 'Gallagher');
INSERT INTO actor (firstname, lastname) VALUES ('Alonzo', 'Brown');
INSERT INTO actor (firstname, lastname) VALUES ('Matt', 'McCoy');
INSERT INTO actor (firstname, lastname) VALUES ('Richmond', 'Arquette');
INSERT INTO actor (firstname, lastname) VALUES ('Henry', 'Fonda');
INSERT INTO actor (firstname, lastname) VALUES ('Grace', 'Kelly');
INSERT INTO actor (firstname, lastname) VALUES ('Ted', 'Tally');
INSERT INTO actor (firstname, lastname) VALUES ('Claude', 'Rains');
INSERT INTO actor (firstname, lastname) VALUES ('Anthony', 'Higgins');
INSERT INTO actor (firstname, lastname) VALUES ('Paul', 'Sorvino');
INSERT INTO actor (firstname, lastname) VALUES ('Scott', 'Bakula');
INSERT INTO actor (firstname, lastname) VALUES ('George', 'Lucas');
INSERT INTO actor (firstname, lastname) VALUES ('Zia', 'Mohyeddin');
INSERT INTO actor (firstname, lastname) VALUES ('Bob', 'Baker (II)');
INSERT INTO actor (firstname, lastname) VALUES ('Bob', 'Gunton');
INSERT INTO actor (firstname, lastname) VALUES ('Frank', 'Vincent');
INSERT INTO actor (firstname, lastname) VALUES ('Tom', 'Rosqui');
INSERT INTO actor (firstname, lastname) VALUES ('Jack', 'Gwyllim');
INSERT INTO actor (firstname, lastname) VALUES ('Bruno', 'Kirby');
INSERT INTO actor (firstname, lastname) VALUES ('Rosemary', 'Murphy');
INSERT INTO actor (firstname, lastname) VALUES ('John', 'Fiedler (I)');
INSERT INTO actor (firstname, lastname) VALUES ('Mike', 'Starr (I)');
